apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playground
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/eMahmoud2021/argocd-app.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    syncOptions:
    - createNNamespace=true
    automated:
      selfHeal: true
      prune: true
  

